variables:
  baseName: adbsccstd0419
  env: dev
  resourcegroup: rg-centralindia-$(baseName)-dev
  vnetresourcegroup: rg-centralindia-$(baseName)-net-dev
  transitresourcegroup: rg-centralindia-$(baseName)-trans-dev
  vnetname: $(baseName)$(env)-vnet
  location: centralindia
